from pathlib import Path
import json,re
ROOT=Path(__file__).resolve().parents[2]
css=re.search(r'<style>(.*?)</style>',(ROOT/'docs/html/01-overview.html').read_text(encoding='utf-8'),re.S).group(1)
content='''<div class="note good">后续更新：E阶段首测已完成，千人ETL通过、万人生成成功但ETL受内存限制。<a href="10-scale.html">查看第十章</a>。</div><section><span class="tag">D 阶段 · 本轮可靠性扩展完成</span><h2>这次验证的是：失败后数据还能不能信</h2><p class="lead">新增13个故障与边界用例，找出并修复2个问题。全项目45项测试通过，包含真实PostgreSQL事务测试。</p><div class="grid"><div class="block"><span class="metric">13</span>新增测试用例</div><div class="block"><span class="metric">2</span>实际发现并修复的问题</div><div class="block"><span class="metric">45</span>全项目测试通过</div></div><p>数据库故障测试使用随机隔离schema，不修改主批次。当前主库仍发布stage-c-verified；官方样本已另行回归。</p></section>
<section><h2>实际问题一：重复表头会悄悄改字段</h2><pre>Id,BIRTHDATE,DEATHDATE,GENDER,GENDER
p1,1980-01-01,,M,F</pre><p>以前CSV读取器会留下后一个GENDER，M被F覆盖，后续格式与枚举校验可能都通过。故障测试发现它没有报错。</p><p><strong>修复：</strong>先检查列名是否唯一。重复表头直接拒绝本批次，失败清单记录原因，旧成功批次继续可用。</p></section>
<section><h2>实际问题二：清单列什么，才检查什么</h2><p>旧加载器会逐项校验清单中的哈希，但未确认清单包含全部必需产物。如果清单漏了dim_patient.json，数据库加载仍会继续。</p><p><strong>修复：</strong>先确认9张模型表的JSON与Parquet、3个ODS、处置账本全部具备哈希，再逐项校验。缺项时在连接数据库前拒绝。它防止漏检和意外损坏，并不证明文件来自可信签名者。</p><p><a href="../stage-d/before-fix.txt">查看修复前真实失败记录</a> · <a href="../stage-d/test-results.txt">查看修复后的45项测试结果</a></p></section>
<section><h2>故障放在哪一层？</h2><div class="flow"><div>输入CSV<span>重复表头、行宽不一致、来源文件不唯一 → 拒绝整批，旧发布结果保持</span></div><div class="arrow">↓</div><div>质量与关联<span>非法生日、缺时区、倒置时间 → 隔离错误父级与影像，处置账本仍逐行对账</span></div><div class="arrow">↓</div><div>文件写入与发布<span>Parquet中途写入失败、指针替换失败 → FAILED清单保留，新run_id可重跑</span></div><div class="arrow">↓</div><div>数据库加载<span>篡改、漏哈希、失败清单 → 连接前拒绝；写入后段异常 → 整批事务回滚</span></div><div class="arrow">↓</div><div>API读取<span>新批次尚未提交或已失败 → 继续读旧批次；重试提交成功 → 切换新批次</span></div></div></section>
<section><h2>一次完整的失败与恢复演练</h2><ol><li>文件和数据库先发布old批次，作为可靠基线。</li><li>准备new文件快照；数据库开始加载它，已写入前面多张表。</li><li>在ADS写入前，用独立API连接读取：仍显示old。</li><li>注入异常，使new事务失败；检查所有相关表，new记录数均为0。</li><li>撤销故障，重新加载同一new文件，发布成功。</li><li>再次加载old只返回已加载，不把当前版本倒退；同ID清单被改变则拒绝。</li></ol><div class="note">old/new是测试批次名，测试在临时文件与隔离schema内运行。这里测的是事务未提交期间的另一连接读取，不是多发布者并发压力。</div></section>
<section><h2>文件成功，数据库失败怎么办？</h2><div class="table-wrap"><table><thead><tr><th>时点</th><th>文件当前批次</th><th>数据库/API当前批次</th></tr></thead><tbody><tr><td>原基线</td><td>old</td><td>old</td></tr><tr><td>新文件完成，连接数据库失败</td><td>file-ready</td><td>old</td></tr><tr><td>连接恢复，补加载成功</td><td>file-ready</td><td>file-ready</td></tr></tbody></table></div><p>这是两个发布步骤，不是分布式事务。恢复时读取已有SUCCESS目录并重新加载；测试确认恢复前后该目录每个文件的哈希完全相同，无需重新跑ETL。</p><details><summary>恢复命令与适用条件</summary><pre>.\\.venv\\Scripts\\python.exe -m scripts.local_postgres start
.\\.venv\\Scripts\\python.exe -m src.database.synthea_store --run-dir output/synthea/runs/stage-c-verified</pre><p>上述目录是当前成功批次，重复执行会返回已加载。实际故障时替换为对应SUCCESS目录；不要加载FAILED目录，不要修改历史清单绕过检查。</p></details></section>
<section><h2>官方样本有没有受到影响？</h2><p>修复后重新处理官方样本到独立验证目录，仍得到108患者、5,571就诊、413检查、413序列、478实例和401日模态组。12位零影像患者完整保留；源数据隔离与重复均为0。</p><p>原主批次通过新版加载器并返回ALREADY_LOADED，17项数据库/API核验再次通过。此前6,092个FHIR摘要资源产物保持原样，FHIR测试包含在本次45项回归中。</p><p>独立重跑目录：<code>output/stage-d-validation/runs/stage-d-verified</code>。一次文件ETL约0.95秒，仅作功能回归记录，不用于性能结论。</p></section>
<section><h2>面试回答：你实际遇到过什么问题？</h2><div class="block"><p>“我做过分层故障注入，发现重复表头会覆盖字段，导入清单漏哈希也没有被拒绝。修复后，对入口、文件发布、事务回滚和恢复重试都加了测试。”</p><p>“数据库写到后段失败时，另一连接仍能读旧批次，回滚后新批次没有残留。文件成功但数据库连接失败时，可以直接补加载已有快照。这样的验证比只说‘加了try/except’更能说明恢复机制。”</p></div></section>
<section><h2>目前阶段与下一步</h2><p><strong>A/B：</strong>项目复习和数据建模已完成。<strong>C：</strong>数据库/API核心链路与FHIR摘要已验证。<strong>D：</strong>本轮13项可靠性扩展已完成。<strong>下一步E：</strong>固定生成版本、seed及参数，分级生成千/万患者并记录实际规模和资源用量。</p><p>本次用受控异常模拟故障，没有实际断电、填满磁盘或杀掉数据库。进程强杀、备份恢复、多发布者并发、长期负载和完整FHIR服务仍待验证。</p><p><a href="../stage-d/README.md">完整测试矩阵与恢复说明</a> · <a href="../stage-d/verification.json">样本回归证据</a> · <a href="../PROGRESS.md">最新进度</a></p></section>'''
nav='<a href="01-overview.html">项目全貌</a><a href="08-fhir.html">FHIR流转</a><a href="09-reliability.html" aria-current="page">异常与恢复</a><a href="10-scale.html">规模实测</a>'
(ROOT/'docs/html/09-reliability.html').write_text(f'<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>第九章 · 异常与恢复实测</title><style>{css}</style></head><body><header><div class="eyebrow">STAGE D / FAILURE & RECOVERY · 2026.09.20</div><h1>失败的时候，数据如何保持可信</h1><p>两个真实缺陷、十三个新增用例，以及可以复现的恢复步骤。</p></header><nav>{nav}</nav><main>{content}<footer class="footer"><a href="08-fhir.html">← FHIR资源流转</a><a href="04-roadmap.html">阶段路线 →</a></footer></main></body></html>',encoding='utf-8')
print('Stage D HTML rendered')
